@isTest
private class NewDiscussionBoardAvailableTest { 
/*

public static User user_admin{


get{
if(user_admin == null){
Profile p = [SELECT Id FROM profile WHERE name='System Administrator'];
user_admin = new User(alias = 'dB1', email='testUserDB1@testorg.com',
emailencodingkey='UTF-8', lastname='Testing', 
languagelocalekey='en_US',IsActive=true,
localesidkey='en_US', profileid = p.Id,Bulletin_Board__c=true,
timezonesidkey='America/Los_Angeles',username='dB1@testorg.com');
insert user_admin;

}

return user_admin;
}
set;
}


static testMethod void testNewDiscussionBoardAvailableTrigger() {
System.assertEquals(User_admin.Bulletin_Board__c, true);

Discussion_Board__c  NewD = new Discussion_Board__c();
NewD.Name = 'TestDB';
//NewD.CurrencyIsoCode = 'USD - U.S.Dollar';
//NewD.Bulletin_Board_Date__c = Now();
NewD.Full_Content__c='Test';
NewD.Active__c = true;
insert NewD;
System.assertNotEquals(User_admin.Bulletin_Board__c, false);
}
*/
}